export const DOWNLOAD_PLAYLIST = "DOWNLOAD_PLAYLIST";

export const ADD_DOWNLOAD = "ADD_DOWNLOAD";
export const CANCEL_DOWNLOAD = "CANCEL_DOWNLOAD";
export const REMOVE_DOWNLOAD = "REMOVE_DOWNLOAD";
export const CHROME_DOWNLOAD = "CHROME_DOWNLOAD";
export const DOWNLOAD_FINISHED = "DOWNLOAD_FINISHED";
export const DOWNLOAD_FAILED = "DOWNLOAD_FAILED";
export const DOWNLOAD_CHANGE = "DOWNLOAD_CHANGE";
