packages:
  - src/background
  - src/core
  - src/design-system
  - src/popup
ignoredBuiltDependencies:
  - esbuild
overrides:
  vite@>=5.2.0 <5.2.14: '>=5.2.14'
  esbuild@<=0.24.2: '>=0.25.0'
  vite@>=5.0.0 <=5.4.11: '>=5.4.12'
  vite@>=5.0.0 <5.4.15: '>=5.4.15'
  vite@>=5.0.0 <5.4.16: '>=5.4.16'
  vite@>=5.0.0 <5.4.18: '>=5.4.18'
  vite@>=5.0.0 <=5.4.18: '>=5.4.19'
  vite@>=5.0.0 <5.4.17: '>=5.4.17'
