name: "Release"

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.12.0"
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y zip
          npm install --global pnpm@10.34.4
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Audit dependencies
        run: pnpm run security:audit
      - name: Typecheck
        run: pnpm run typecheck
      - name: Build all variants
        run: pnpm run build:all-variants
      - name: Test
        run: pnpm test
      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          fail_on_unmatched_files: true
          overwrite_files: true
          files: |
            dist/extension-mv2-chrome.zip
            dist/extension-mv2-firefox.xpi
            dist/extension-mv3-chrome.zip
            dist/extension-mv2-no-blocklist-chrome.zip
            dist/extension-mv2-no-blocklist-firefox.xpi
            dist/extension-mv3-no-blocklist-chrome.zip
