name: "Release"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Enable corepack
        run: corepack enable
      - name: Prepare pnpm
        run: corepack prepare pnpm@10.11.0 --activate
      - name: Install dependencies
        run: pnpm install
      - name: Clean workspace
        run: pnpm run clean
      - name: Build MV2
        run: pnpm run build:mv2
      - name: Build MV3
        run: pnpm run build:mv3
      - name: Test
        run: pnpm test
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/extension-mv2-chrome.zip
            dist/extension-mv2-firefox.xpi
            dist/extension-mv3-chrome.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
